<script setup lang="ts">
import UnitsConverter from '@/components/UnitsConverter.vue';

const supportedUnits = {
  'm³': { value: 'cubic meter/stere', label: 'cubic meter/stere' },
  'Pm³': { value: 'cubic petameter', label: 'cubic petameter' },
  'Tm³': { value: 'cubic terameter', label: 'cubic terameter' },
  'Gm³': { value: 'cubic gigameter', label: 'cubic gigameter' },
  'Mm³': { value: 'cubic megameter', label: 'cubic megameter' },
  'km³': { value: 'cubic kilometer', label: 'cubic kilometer' },
  'hm³': { value: 'cubic hectometer', label: 'cubic hectometer' },
  'dam³': { value: 'cubic decameter', label: 'cubic decameter' },
  'dm³': { value: 'cubic decimeter', label: 'cubic decimeter' },
  'cm³': { value: 'cubic centimeter', label: 'cubic centimeter' },
  'mm³': { value: 'cubic millimeter', label: 'cubic millimeter' },
  'µm³': { value: 'cubic micrometer', label: 'cubic micrometer' },
  'nm³': { value: 'cubic nanometer', label: 'cubic nanometer' },
  'pm³': { value: 'cubic picometer', label: 'cubic picometer' },
  'fm³': { value: 'cubic femtometer', label: 'cubic femtometer' },
  L: { value: 'liter', label: 'liter' },
  Pl: { value: 'petaliter', label: 'petaliter' },
  Tl: { value: 'teraliter', label: 'teraliter' },
  Gl: { value: 'gigaliter', label: 'gigaliter' },
  Ml: { value: 'megaliter', label: 'megaliter' },
  kL: { value: 'kiloliter', label: 'kiloliter' },
  hL: { value: 'hectoliter', label: 'hectoliter' },
  daL: { value: 'decaliter', label: 'decaliter' },
  dL: { value: 'deciliter', label: 'deciliter' },
  cL: { value: 'centiliter', label: 'centiliter' },
  mL: { value: 'milliliter', label: 'milliliter' },
  µL: { value: 'microliter', label: 'microliter' },
  nL: { value: 'nanoliter', label: 'nanoliter' },
  pL: { value: 'picoliter', label: 'picoliter' },
  fL: { value: 'femtoliter', label: 'femtoliter' },
  'mi³': { value: 'cubic mile', label: 'cubic mile' },
  'ac ft': { value: 'acre-foot', label: 'acre-foot' },
  'yd³': { value: 'cubic yard', label: 'cubic yard' },
  'ft³': { value: 'cubic foot', label: 'cubic foot' },
  'board feet': { value: 'board feet', label: 'board feet' },
  'in³': { value: 'cubic inch', label: 'cubic inch' },
  MTON: { value: 'measurement ton', label: 'measurement ton' },
  'imp bbl': { value: 'imperial barrel', label: 'imperial barrel' },
  'imp bsh': { value: 'imperial bushel', label: 'imperial bushel' },
  pk: { value: 'imperial peck', label: 'imperial peck' },
  'imp gal': { value: 'imperial gallon', label: 'imperial gallon' },
  'imp qt': { value: 'imperial quart', label: 'imperial quart' },
  'imp pt': { value: 'imperial pint', label: 'imperial pint' },
  'imp fl oz': { value: 'imperial fluid ounce', label: 'imperial fluid ounce' },
  tsp: { value: 'teaspoon', label: 'teaspoon' },
  tbsp: { value: 'tablespoon', label: 'tablespoon' },
  'fl oz': { value: 'US fluid ounce', label: 'US fluid ounce' },
  c: { value: 'cup', label: 'cup' },
  'US lc': { value: 'US legal cup', label: 'US legal cup' },
  pt: { value: 'US liquid pint', label: 'US liquid pint' },
  qt: { value: 'US liquid quart', label: 'US liquid quart' },
  gal: { value: 'US liquid gallon', label: 'US liquid gallon' },
  'US bsh': { value: 'US bushel', label: 'US bushel' },
  'US pk': { value: 'US peck', label: 'US peck' },
  'US dry gal': { value: 'US dry gallon', label: 'US dry gallon' },
  'US dry bbl': { value: 'US dry barrel', label: 'US dry barrel' },
  'US dry qt': { value: 'US dry quart', label: 'US dry quart' },
  'US dry pt': { value: 'US dry pint', label: 'US dry pint' },
};
</script>

<template>
  <UnitsConverter default-unit="m³" :supported-units="supportedUnits" label-width="150px" />
</template>
